### ISSUE TITLE
Injector doesn't resolve providers in extended class constructors

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#211]
Given the following (most minimal example I can provide): 

```ts
class A {}

class B {
  constructor(readonly a: A) {
    // a is undefined
  }
}

class C extends B {}

class SomeModule extends createModule({
  providers: [
    A,
    C,
  ],
}) {}
```

It's unable to resolve the class `A` provider in class `B` when it's extended by class `C`.

**Comment by marcus-sa** [comment]
Sure @marcj 

The repository is at https://github.com/convoy-js/convoy

Steps:
- `$ yarn`
- Remove the line at https://github.com/convoy-js/convoy/blob/main/examples/kafka/project.json#L36 so that you don't have to run docker containers
- `$ yarn nx serve examples-kafka`

You'll then see this error in the terminal
```
TypeError: Cannot read properties of undefined (reading 'consumer')
```

Which is due to [this](https://github.com/convoy-js/convoy/blob/cd39e252478260dacc5cab270b965289687b6c91/packages/kafka/deepkit/src/lib/deepkit-kafka-message-consumer.ts#L14-L17) being commented out.

If you want to know where the class is being provided, then it's [here](https://github.com/convoy-js/convoy/blob/cd39e252478260dacc5cab270b965289687b6c91/packages/kafka/deepkit/src/lib/kafka-message.module.ts#L58-L62)

**Comment by marcus-sa** [comment]
@marcj after realizing I might've forgot to add `"reflection": true` to `@convoy/kafka`'s [tsconfig.json](https://github.com/convoy-js/convoy/blob/cd39e252478260dacc5cab270b965289687b6c91/packages/kafka/tsconfig.json), I now get a different error:
```
TypeError: Cannot create property 'parent' on string 'offsetsToCommit'
    at Processor.loop (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/processor.ts:555:42)
    at Processor.runProgram (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/processor.ts:379:25)
    at Processor.run (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/processor.ts:367:21)
    at Processor.reflect (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/processor.ts:357:27)
    at resolveRuntimeType (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/processor.ts:130:34)
    at Function.from (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/reflection.ts:1211:114)
    at Function.from (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/type/src/reflection/reflection.ts:1222:139)
    at Injector.createFactory (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/injector/src/injector.ts:464:49)
    at Injector.buildProvider (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/injector/src/injector.ts:363:28)
    at Injector.build (/Users/marcus-sa/Git/convoy/convoy/node_modules/@deepkit/injector/src/injector.ts:291:37)

```

**Comment by marcj** [comment]
That error `at Processor.loop` seems like a bug. how did you fix that? :)

**Comment by marcus-sa** [comment]
@marcj the method at https://github.com/convoy-js/convoy/blob/cd39e252478260dacc5cab270b965289687b6c91/packages/kafka/src/lib/kafka-message-processor.ts#L54 references a class return type that has a comment above it `// @entity.name('topic-partition-offset')` which the type compiler didn't seem to respect.
After removing the lines at https://github.com/convoy-js/convoy/blob/cd39e252478260dacc5cab270b965289687b6c91/packages/kafka/src/lib/topic-partition-offsets.ts#L1-L3 it resolved.
