### ISSUE TITLE
[Bug] Interface Dependency Injection Fails when the Implementation Has Methods with Explicit `Promise` Return Value

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#218]
When there is a method(sync or async) with an explicit `Promise` return value in the implementation of an interface, dependency injection of the interface will fail.

## Reproduce

```ts
interface Dependency {
  test(): Promise<void>;
}

class AppDependency implements Dependency {
  test(): Promise<void> {
    return Promise.resolve();
  }
}

class AppService {
  constructor(private dep: Dependency) {}
}

new App({
  providers: [AppService, AppDependency],
}).run();
```

```
DependenciesUnmetError: Undefined dependency "dep: Dependency" of AppService(?). Type has no provider in no scope.
    at Injector.createFactoryProperty (/home/.../node_modules/@deepkit/injector/src/injector.ts:625:19)
    at Injector.createFactory (/home/.../node_modules/@deepkit/injector/src/injector.ts:476:32)
    at Injector.buildProvider (/home/.../node_modules/@deepkit/injector/src/injector.ts:363:28)
    at Injector.build (/home/.../node_modules/@deepkit/injector/src/injector.ts:291:37)
    at new Injector (/home/.../node_modules/@deepkit/injector/src/injector.ts:201:14)
    at RootAppModule.getOrCreateInjector (/home/.../node_modules/@deepkit/injector/src/module.ts:356:25)
    at InjectorContext.getInjector (/home/.../node_modules/@deepkit/injector/src/injector.ts:858:23)
    at InjectorContext.getRootInjector (/home/.../node_modules/@deepkit/injector/src/injector.ts:862:21)
    at ServiceContainer.process (/home/.../node_modules/@deepkit/app/src/service-container.ts:95:30)
    at ServiceContainer.getInjectorContext (/home/.../node_modules/@deepkit/app/src/service-container.ts:115:14)
```

## Additional Information

It works well when the async method's return value `Promise<void>` is implicit in the implementation:

```ts
import { App } from '@deepkit/app';

export interface Dependency {
  test(): Promise<void>;
}

export class AppDependency implements Dependency {
  test() {
    return Promise.resolve();
  }
}

class AppService {
  constructor(private dep: Dependency) {}
}

new App({
  providers: [AppService, AppDependency],
}).run();
```

It works well when the method's explicit return value is not a `Promise`:

```ts
import { App } from '@deepkit/app';

export interface Dependency {
  test(): void;
}

export class AppDependency implements Dependency {
  test(): void {}
}

class AppService {
  constructor(private dep: Dependency) {}
}

new App({
  providers: [AppService, AppDependency],
}).run();
```

**Comment by marcj** [comment]
Fixed in https://github.com/deepkit/deepkit-framework/commit/30939492b96fd90d027728fc7a3030e8d8d24bf3
