### ISSUE TITLE
[Bug] Factory Providers Cannot Use `Inject<Type, Token>`

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#240]
```ts
import { App } from "@deepkit/app";
import { Inject } from "@deepkit/injector";

new App({
  providers: [
    { provide: "null", useValue: null },
    { provide: "test", useFactory: (dep: Inject<null, "null">) => dep },
  ],
}).run();
```
```
ts-node src/app.ts

DependenciesUnmetError: Undefined dependency "dep: Inject<null, 'null'>" of useFactory(?). Type has no provider in no scope.
    at Injector.createFactoryProperty (/.../project/node_modules/@deepkit/injector/src/injector.ts:625:19)
    at Injector.buildProvider (/.../project/node_modules/@deepkit/injector/src/injector.ts:374:32)
    at Injector.build (/.../project/node_modules/@deepkit/injector/src/injector.ts:291:37)
    at new Injector (/.../project/node_modules/@deepkit/injector/src/injector.ts:201:14)
    at RootAppModule.getOrCreateInjector (/.../project/node_modules/@deepkit/injector/src/module.ts:356:25)
    at InjectorContext.getInjector (/.../project/node_modules/@deepkit/injector/src/injector.ts:858:23)
    at InjectorContext.getRootInjector (/.../project/node_modules/@deepkit/injector/src/injector.ts:862:21)
    at ServiceContainer.process (/.../project/node_modules/@deepkit/app/src/service-container.ts:95:30)
    at ServiceContainer.getInjectorContext (/.../project/node_modules/@deepkit/app/src/service-container.ts:115:14)
    at App.getInjectorContext (/.../project/node_modules/@deepkit/app/src/app.ts:259:38)
```

**Comment by marcj** [comment]
Fixed in https://github.com/deepkit/deepkit-framework/commit/7fe644a02b5da4ee0a73f6d87e14d6648b939540
