### ISSUE TITLE
[Bug] Database Insertion Fails If `ReflectionProperty.getResolvedReflectionClass()` Is Called Before Database Instantiation

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#255]
# Reproducing

- `ReflectionProperty.getResolvedReflectionClass()` is called on a reference field before database instantiation
- there are some other fields except of the primary key and the relation field (`name` in this case)

```ts
import { Database } from "@deepkit/orm";
import { SQLiteDatabaseAdapter } from "@deepkit/sqlite";
import {
  AutoIncrement,
  BackReference,
  PrimaryKey,
  Reference,
  ReflectionClass,
} from "@deepkit/type";

async function main() {
  class User {
    id: number & AutoIncrement & PrimaryKey = 0;
    name: string = "";
    books: Book[] & BackReference = [];
  }
  class Book {
    id: number & AutoIncrement & PrimaryKey = 0;
    owner!: User & Reference;
  }
  ReflectionClass.from(Book)
    .getProperty("owner")
    .getResolvedReflectionClass()
    .getPrimary();
  const database = new Database(new SQLiteDatabaseAdapter(), [User, Book]);
  await database.migrate();
  const user = new User();
  await database.persist(user);
}

main();
```

```
/home/.../example/node_modules/@deepkit/sqlite/src/sqlite-adapter.ts:144
            const result = stmt.run(...params);
                                ^
SqliteError: NOT NULL constraint failed: User.name
    at SQLiteConnection.run (/home/.../example/node_modules/@deepkit/sqlite/src/sqlite-adapter.ts:144:33)
    at SQLitePersistence.batchInsert (/home/.../example/node_modules/@deepkit/sql/src/sql-adapter.ts:809:48)
    at async SQLitePersistence.doInsert (/home/.../example/node_modules/@deepkit/sql/src/sql-adapter.ts:737:13)
    at async SQLitePersistence.insert (/home/.../example/node_modules/@deepkit/sql/src/sql-adapter.ts:718:9)
    at async DatabaseSessionRound.doPersist (/home/.../example/node_modules/@deepkit/orm/src/database-session.ts:192:25)
    at async DatabaseSessionRound.commit (/home/.../example/node_modules/@deepkit/orm/src/database-session.ts:114:13)
    at async DatabaseSession.flush (/home/.../example/node_modules/@deepkit/orm/src/database-session.ts:519:17)
    at async DatabaseSession.commit (/home/.../example/node_modules/@deepkit/orm/src/database-session.ts:329:9)
    at async Database.persist (/home/.../example/node_modules/@deepkit/orm/src/database.ts:325:9)
    at async main (/home/.../example/src/app.ts:53:3) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
```

# Behavior

Error happens in `@deepkit/sql/src/sql-adapter.ts:SQLPersistence:batchInsert`:

```ts
    protected async batchInsert<T>(classSchema: ReflectionClass<T>, items: T[]) {
        const scopeSerializer = getSerializeFunction(classSchema.type, this.platform.serializer.serializeRegistry);
        const insert: string[] = [];
        const params: any[] = [];
        this.resetPlaceholderSymbol();
        const names: string[] = [];

        for (const property of classSchema.getProperties()) {
            // if (property.isParentReference) continue;
            if (property.isBackReference()) continue;
            if (property.isAutoIncrement()) continue;
            names.push(this.platform.quoteIdentifier(property.name));
        }

        for (const item of items) {
            const converted = scopeSerializer(item);

            const row: string[] = [];
            for (const property of classSchema.getProperties()) {
                // if (property.isParentReference) continue;
                if (property.isBackReference()) continue;
                if (property.isAutoIncrement()) continue;

                const v = converted[property.name];
                params.push(v === undefined ? null : v);
                row.push(this.getPlaceholderSymbol());
            }

            insert.push(row.join(', '));
        }

        const sql = this.getInsertSQL(classSchema, names, insert);
        try {
            await (await this.getConnection()).run(sql, params);
        } catch (error) {
            throw error;
        }
    }
```
![image](https://user-images.githubusercontent.com/63489409/172019515-9fbf3496-6d2e-47b6-b635-05584b68c20c.png)
![image](https://user-images.githubusercontent.com/63489409/172019519-ae6ec112-f155-4de1-98da-b099d770eadc.png)
![image](https://user-images.githubusercontent.com/63489409/172019556-a9f5b4d9-bccd-47ba-ac68-07be2f61b4fb.png)
![image](https://user-images.githubusercontent.com/63489409/172019523-e5228d7a-10b5-4e20-8d67-22c8a36514d5.png)

**Comment by TheNightmareX** [comment]
# Workaround

It is caused by a `Reference` type-decorator that is mistakenly added.

So we can work around it by removing the decorator:

```
const reflection =   ReflectionClass.from(Book)
    .getProperty("owner")
    .getResolvedReflectionClass()
    .getPrimary();
reflection.type.decorators = undefined;
```

**Comment by TheNightmareX** [comment]
Found a `Reference` type-decorator is mistakenly applied to `User` in this case.

Although this still not work, it makes the process behave better.

```ts
  const r = ReflectionClass.from(Book)
    .getProperty("owner")
    .getResolvedReflectionClass();
  r.type.decorators = undefined;
  r.type.annotations = undefined;
```

**Comment by TheNightmareX** [comment]
Found that `parent` is also mistakenly defined to `owner`. This time the workaround finally worked:

```ts
  const r = ReflectionClass.from(Book)
    .getProperty("owner")
    .getResolvedReflectionClass();
  r.type.decorators = undefined;
  r.type.annotations = undefined;
  r.type.parent = undefined;
```

**Comment by TheNightmareX** [comment]
Well the true point is:

```ts
  const userType = ReflectionClass.from(Book)
    .getProperty("owner")
    .getResolvedReflectionClass();
  const bookOwnerType = ReflectionClass.from(Book).getProperty("owner");
  console.debug(userType.type === bookOwnerType.type); // true
```

they share the same type instance.

So the previous workaround still not work on relation fields.

**Comment by TheNightmareX** [comment]
`ReflectionClass.from()` will cache the reflection result at the `classType.prototype`. So if we call `ReflectionProperty.getResolvedReflectionClass(User)` before `ReflectionClass.from(User)`, the reflection result with decorated type object will be cached and thus break the application.

So this is the final workaround: Call `ReflectionClass.from()` immediately after you've defined your entity class.

**Comment by TheNightmareX** [comment]
close as fixed
