### ISSUE TITLE
[Bug] `Database` Cannot Be an Injection Token when `debug` is enabled in `FrameworkModule`

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#260]
Happens only when `debug` is enabled.

```ts
import { App } from "@deepkit/app";
import { FrameworkModule } from "@deepkit/framework";
import { Database } from "@deepkit/orm";

new App({
  imports: [new FrameworkModule({ debug: true })],
  providers: [{ provide: Database, useValue: "anything" }],
}).run();
```

```
ts-node src/app.ts

Error: No valid runtime type for Database given. Is @deepkit/type-compiler correctly installed? Execute deepkit-type-install to check
    at Processor.reflect (/home/char2s/projects/Cridium/server/node_modules/@deepkit/type/src/reflection/processor.ts:319:19)
    at resolveRuntimeType (/home/char2s/projects/Cridium/server/node_modules/@deepkit/type/src/reflection/processor.ts:130:34)
    at resolveReceiveType (/home/char2s/projects/Cridium/server/node_modules/@deepkit/type/src/reflection/reflection.ts:81:49)
    at FrameworkModule.setupProvider (/home/char2s/projects/Cridium/server/node_modules/@deepkit/injector/src/module.ts:329:48)
    at FrameworkModule.setupDatabase (/home/char2s/projects/Cridium/server/node_modules/@deepkit/framework/src/module.ts:205:22)
    at FrameworkModule.postProcess (/home/char2s/projects/Cridium/server/node_modules/@deepkit/framework/src/module.ts:195:14)
    at ServiceContainer.postProcess (/home/char2s/projects/Cridium/server/node_modules/@deepkit/app/src/service-container.ts:101:15)
    at ServiceContainer.process (/home/char2s/projects/Cridium/server/node_modules/@deepkit/app/src/service-container.ts:92:14)
    at ServiceContainer.getInjectorContext (/home/char2s/projects/Cridium/server/node_modules/@deepkit/app/src/service-container.ts:115:14)
    at App.getInjectorContext (/home/char2s/projects/Cridium/server/node_modules/@deepkit/app/src/app.ts:259:38)
```

**Comment by marcj** [comment]
Could you try current master?

**Comment by TheNightmareX** [comment]
close as fixed
