### ISSUE TITLE
"reflection": true causes patched tsc to crash in this input

### ISSUE THREAD

**Issue by espindola** [deepkit/deepkit-framework#283]
```
export default function(bar: string) {
    return bar;
}
```

**Comment by marcj** [comment]
What's the error message?

**Comment by espindola** [comment]
> What's the error message?

```
]% ../deepkit-framework/node_modules/typescript/bin/tsc hello.ts
/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:95322
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at isOuterExpression (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:23435:22)
    at Object.skipOuterExpressions (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:23454:16)
    at Object.skipPartiallyEmittedExpressions (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:9687:19)
    at Object.parenthesizeLeftSideOfAccess (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:16868:40)
    at createPropertyAccessExpression (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:18612:52)
    at factory.createPropertyAccessExpression (/home/espindola/chisel/deepkit-framework/node_modules/typescript/lib/tsc.js:17207:70)
    at ReflectionTransformer.decorateFunctionDeclaration (/home/espindola/chisel/deepkit-framework/packages/type-compiler/dist/cjs/src/compiler.js:1870:89)
    at visitor (/home/espindola/chisel/deepkit-framework/packages/type-compiler/dist/cjs/src/compiler.js:462:29)
    at visitNodes (/home/espindola/chisel/deepkit-framework/packages/type-compiler/node_modules/typescript/lib/typescript.js:87656:48)
    at visitLexicalEnvironment (/home/espindola/chisel/deepkit-framework/packages/type-compiler/node_modules/typescript/lib/typescript.js:87696:22)
```

**Comment by marcj** [comment]
Thanks for the report! Fixed in https://github.com/deepkit/deepkit-framework/commit/639915257679e9bb7ad4d715a603de11bdd66063
