### ISSUE TITLE
Cannot reproduce  packages/http/tests/router.spec.ts  failure

### ISSUE THREAD

**Issue by espindola** [deepkit/deepkit-framework#301]
The test failed in a run in:

https://pipelines.actions.githubusercontent.com/serviceHosts/631e7b9e-7135-4d87-a6d9-d9dd035026a0/_apis/pipelines/1/runs/418/signedlogcontent/2?urlExpires=2022-07-12T08%3A46%3A17.7498912Z&urlSigningMethod=HMACV1&urlSignature=m2OXZTcZm%2Fyvy08gRmmjDew%2FVl%2F45S8OZ0Ghr6MuRCI%3D

But I cannot reproduce it locally with
```
$ npm run test    packages/http/tests/router.spec.ts
```

**Comment by marcj** [comment]
Link doesn't work. What's the issue here?

**Comment by espindola** [comment]
The part of the output that is different from running locally is:

```
The part of the output that is different from running locally is:

```
2022-07-11T09:16:09.8273398Z [31mController error Error: Unhandled error. (Error: 
2022-07-11T09:16:09.8274033Z     at Controller.apply [as handle] (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:919:49)
2022-07-11T09:16:09.8274841Z     at HttpListener.onController (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/http.ts:651:39)
2022-07-11T09:16:09.8275654Z     at self (eval at buildAsync (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/node_modules/@deepkit/core/src/compiler.ts:111:20), <anonymous>:172:51)
2022-07-11T09:16:09.8276197Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-11T09:16:09.8276862Z     at HttpKernel.handleRequest (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:42:17)
2022-07-11T09:16:09.8277557Z     at HttpKernel.request (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:25:9)
2022-07-11T09:16:09.8278256Z     at Object.<anonymous> (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:923:23))
2022-07-11T09:16:09.8278704Z     at new NodeError (node:internal/errors:371:5)
2022-07-11T09:16:09.8279031Z     at Readable.emit (node:events:379:17)
2022-07-11T09:16:09.8279642Z     at Controller.apply [as handle] (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:919:35)
2022-07-11T09:16:09.8280362Z     at HttpListener.onController (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/http.ts:651:39)
2022-07-11T09:16:09.8281162Z     at self (eval at buildAsync (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/node_modules/@deepkit/core/src/compiler.ts:111:20), <anonymous>:172:51)
2022-07-11T09:16:09.8281704Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-11T09:16:09.8282348Z     at HttpKernel.handleRequest (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:42:17)
2022-07-11T09:16:09.8283051Z     at HttpKernel.request (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:25:9)
2022-07-11T09:16:09.8283950Z     at Object.<anonymous> (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:923:23) {
2022-07-11T09:16:09.8284363Z   code: 'ERR_UNHANDLED_ERROR',
2022-07-11T09:16:09.8284588Z   context: Error: 
2022-07-11T09:16:09.8285202Z       at Controller.apply [as handle] (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:919:49)
2022-07-11T09:16:09.8285809Z       at HttpListener.onController (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/http.ts:651:39)
2022-07-11T09:16:09.8286479Z       at self (eval at buildAsync (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/node_modules/@deepkit/core/src/compiler.ts:111:20), <anonymous>:172:51)
2022-07-11T09:16:09.8286932Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-11T09:16:09.8287628Z       at HttpKernel.handleRequest (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:42:17)
2022-07-11T09:16:09.8288215Z       at HttpKernel.request (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/src/kernel.ts:25:9)
2022-07-11T09:16:09.8288801Z       at Object.<anonymous> (/home/ubuntu/actions-runner/_work/deepkit-framework/deepkit-framework/packages/http/tests/router.spec.ts:923:23)
2022-07-11T09:16:09.8289210Z }[39m
2022-07-11T09:16:09.8829908Z FAIL packages/http/tests/router.spec.ts (6.446 s)
2022-07-11T09:16:09.8830447Z   ● stream
2022-07-11T09:16:09.8830592Z 
2022-07-11T09:16:09.8833247Z     expect(received).toBe(expected) // Object.is equality
2022-07-11T09:16:09.8833474Z 
2022-07-11T09:16:09.8833674Z     Expected: "test"
2022-07-11T09:16:09.8833839Z     Received: ""
2022-07-11T09:16:09.8833989Z 
2022-07-11T09:16:09.8834375Z       910 |     const response = (await httpKernel.request(HttpRequest.GET('/')));
2022-07-11T09:16:09.8834671Z       911 |     expect(response.statusCode).toBe(200);
2022-07-11T09:16:09.8835038Z     > 912 |     expect(response.bodyString).toBe('test');
2022-07-11T09:16:09.8835312Z           |                                 ^
2022-07-11T09:16:09.8835720Z       913 | });
2022-07-11T09:16:09.8835947Z       914 |
2022-07-11T09:16:09.8836502Z       915 | test('stream error', async () => {
2022-07-11T09:16:09.8836669Z 
2022-07-11T09:16:09.8836882Z       at Object.<anonymous> (tests/router.spec.ts:912:33)
```

**Comment by marcj** [comment]
Ah now I see what you are trying to tell me. If you change the local typescript version, you have to remove all dist files, run "nom run install-compiler", and rebuild from scratch using "npm run build", this takes a while if done correctly. The build server does that so it might get different results than you.

**Comment by espindola** [comment]
I don't think that is the issue. The same test failed at https://github.com/deepkit/deepkit-framework/runs/7278707851?check_suite_focus=true which didn't change typescript. I am pretty sure I did a 'git clean -fxd' locally. Maybe the issue has just been fixed on master. I rebased https://github.com/deepkit/deepkit-framework/pull/297 and pushed it again. Lets see if it passes.

**Comment by marcj** [comment]
If its the stream test then yet this was fixed in master. You should rebase.

**Comment by espindola** [comment]
OK, at least the first PR passed. Thanks.
