### ISSUE TITLE
Deserialization/serialization with a custom naming strategy doesn't work with readonly arrays

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#311]
I haven't tested if it's an issue with the default naming strategy as well.
But the example throws the following error:
```
Validation error:
postComments(type): Cannot convert [object Object] to number
ValidationError: Validation error:
postComments(type): Cannot convert [object Object] to number
    at Function.from (/xxx/node_modules/@deepkit/type/src/validator.ts:104:16)
    at Object.self [as fn] (eval at build (/xxx/node_modules/@deepkit/core/src/compiler.ts:95:20), <anonymous>:43:55)
    at self (eval at build (/xxx/node_modules/@deepkit/core/src/compiler.ts:95:20), <anonymous>:16:20)
    at deserialize (/xxx/node_modules/@deepkit/type/src/serializer-facade.ts:50:12)
```
Reproducable example
```ts
const camelCaseToSnakeCase = (str: string) =>
  str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);

class CamelCaseToSnakeCaseNamingStrategy extends NamingStrategy {
  constructor() {
    super('snake-case-to-camel-case');
  }

  override getPropertyName(
    type: TypeProperty | TypePropertySignature,
    forSerializer: string
  ): string | undefined {
    const propertyName = super.getPropertyName(type, forSerializer);
    return propertyName ? camelCaseToSnakeCase(propertyName) : undefined;
  }
}

class PostComment {
  readonly id: number;
}

class User {
  readonly id: number;
  // no longer throws when removing readonly from array
  readonly postComments: readonly PostComment[];
}

deserialize<User>(
  {
    id: 1,
    post_comments: [
      {
        id: 1,
      },
    ],
  },
  undefined,
  serializer,
  new CamelCaseToSnakeCaseNamingStrategy()
)
```

**Comment by marcj** [comment]
This looks more like a readonly array issue. I'll try to locate the bug
