### ISSUE TITLE
[Bug] Controller API: Could not resolve request

### ISSUE THREAD

**Issue by pavel-voronin** [deepkit/deepkit-framework#313]
## Expected Behavior

Using Controller API and copying code from [documentation](https://docs.deepkit.io/english/http.html#_controller_api) I have working Hello World App that successfully handles `GET /hello` request.

## Current Behavior

Having exactly reproduced the steps in the documentation, I got the following error when trying to request `GET /hello`:

```
2022-07-18T11:15:40.750Z [ERROR] Could not resolve request Error: No method helloWorld found in MyPage
    at ReflectionClass.getMethod (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/type/src/reflection/reflection.ts:1265:28)
    at RouteConfig.getReflectionFunction (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/router.ts:144:58)
    at parseRouteControllerAction (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/router.ts:270:50)
    at HttpRouter.getRouteCode (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/router.ts:675:29)
    at HttpRouter.build (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/router.ts:910:28)
    at HttpRouter.resolveRequest (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/router.ts:951:28)
    at HttpListener.onRoute (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/http.ts:525:42)
    at self (eval at buildAsync (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/core/src/compiler.ts:111:20), <anonymous>:60:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpKernel.handleRequest (/home/pavel/projects/americor/salesrep-reborn/node_modules/@deepkit/http/src/kernel.ts:42:17)
```

## Possible Solution

Correct way to use Controller API should be provided.

## Steps to Reproduce

1. Install Deepkit framework `npm install ts-node @deepkit/framework`
2. Have a `app.ts` file filled using [documentation](https://docs.deepkit.io/english/http.html#_controller_api):
```typescript
import { App } from "@deepkit/app";
import { FrameworkModule } from "@deepkit/framework";
import { http } from "@deepkit/http";

class MyPage {
  @http.GET("/")
  helloWorld() {
    return "Hello World!";
  }
}

new App({
  controllers: [MyPage],
  imports: [new FrameworkModule()],
}).run();
```
3. Start an app with `npx ts-node-script app.ts server:start`
4. Open `http://0.0.0.0:8080/hello` in browser

## Context (Environment)

```
pavel@Legion:~/project$ node -v
v16.16.0
pavel@Legion:~/project$ npm list
project@1.0.0 /home/pavel/project
├── @deepkit/framework@1.0.1-alpha.73
├── ts-node@10.9.1
└── typescript@4.7.4
```

## Detailed Description

**[Functional API](https://docs.deepkit.io/english/http.html#_funktionale_api) is working!**

But I prefer Controller API...

## Possible Implementation

Sorry, don't know

**Comment by timvandam** [comment]
Try annotating MyPage with `@http.controller()`

**Comment by marcj** [comment]
deepkit/framework depends in runtime types (deepkit/type) which has not been installed in your example. Please follow the documentation where it says that you first have to install runtime types.
