### ISSUE TITLE
Unable to run Jest importing FrameworkModule (breaks on .ts file node_modules)

### ISSUE THREAD

**Issue by CristianPi** [deepkit/deepkit-framework#371]
test file

```typescript

import {App} from '@deepkit/app';
import {FrameworkModule} from '@deepkit/framework'; // this breaks jest?!

export async function bootstrap() {
  const app = new App({});

  // framework module
  const port: number = parseInt(process.env.PORT) || 5001;

  app.appModule.addImport(new FrameworkModule({
    port,
  }));

  await app
    .loadConfigFromEnv()
    .run(["server:start"]);

  return app;
}

//bootstrap();


describe('boot', () => {
  it('boot', async () => {
      await new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(true)
        },1000)
      })
  });
});


```

error

```bash

 FAIL   api  apps/api/test/example2.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/cristian/IdeaProjects/climbo2/node_modules/@deepkit/sql/commands.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './src/cli/migration-create-command';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/@deepkit/framework/src/module.ts:32:1)

```

**Comment by marcj** [comment]
`commands.ts` is used in special package export here https://github.com/deepkit/deepkit-framework/blob/master/packages/sql/package.json#L15, so it should never be used in your code.
So looks like a jest/ts-jest error rather than a deepkit error, so I'd report it there.

**Comment by CristianPi** [comment]
Good to know, i have to check Nx then, maybe there's a bug with the loader,
although it happens only with that import.

**Comment by marcj** [comment]
It's also weird that is doesn't print `dist/cjs/commands.js` but `sql/commands.ts` as if the TS source file is wrongly imported somewhere by jest/ts-jest.

**Comment by CristianPi** [comment]
updating to Nx v. 14.7.3 solved the problem (they changed jest config and updated the pkg)
