### ISSUE TITLE
How to install the latest version in github?

### ISSUE THREAD

**Issue by ssine** [deepkit/deepkit-framework#384]
I ran into the same problem as https://github.com/deepkit/deepkit-framework/issues/342 and found that the fix was not yet published to npm registry.

I tried to install from the repo directly but the cjs package is missing:

```
Error: Cannot find module '.../node_modules/@deepkit/mongo/dist/cjs/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:483:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/sine/code/DramaVerse/queen-backend/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sine/code/DramaVerse/queen-backend/src/data.ts:1:1) {
  code: 'MODULE_NOT_FOUND',
```

How can I install it properly?

BTW, https://www.npmjs.com/package/@deepkit/form-integration seems to be missing at the moment.

**Comment by marcj** [comment]
That's not easily possible and not something we recommend. a package named `@deepkit/form-integration)` does not exist
