### ISSUE TITLE
Dependency injection of "abstract" Database doesn't work

### ISSUE THREAD

**Issue by colorcube** [deepkit/deepkit-framework#396]
Dependency injection doesn't work when _Database_ is used in constructor. 
When using the type of the implementation class, like _SQLiteDatabase_, it's working.

I think that isn't intentional. An implementation of Database ist provided. DI should resolve that and inject _SQLiteDatabase_ into the constructor with type _Database_.

Example which doesn't work

```typescript
export class SQLiteDatabase extends Database {
  constructor() {
    super(new SQLiteDatabaseAdapter('/tmp/test.db'), [User, Book, Author]);
  }
}

@http.controller()
export class HelloController {
  constructor(protected database: Database) {}

  @http.GET('/api/hello')
  async hello() {
    const user = await this.database.query(User).find();
    console.log('all user', user);

    return 'Hello there!';
  }
}

new App({
  controllers: [HelloController],
  imports: [
    new FrameworkModule({
      debug: true,
      httpLog: true,
      migrateOnStartup: true,
    }),
  ],
  providers: [SQLiteDatabase]
})
  .loadConfigFromEnv()
  .run();
```  

```
DependenciesUnmetError: Undefined dependency "database: Database<DatabaseAdapter>" of HelloController(?). Type has no provider in scope http.
    at Injector.createFactoryProperty (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:661:19)
    at Injector.createFactory (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:511:32)
    at Injector.buildProvider (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:397:28)
    at Injector.build (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:325:37)
    at new Injector (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:227:14)
    at RootAppModule.getOrCreateInjector (/var/www/deepkit-test/node_modules/@deepkit/injector/src/module.ts:359:25)
    at InjectorContext.getInjector (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:885:23)
    at InjectorContext.getRootInjector (/var/www/deepkit-test/node_modules/@deepkit/injector/src/injector.ts:889:21)
    at ServiceContainer.process (/var/www/deepkit-test/node_modules/@deepkit/app/src/service-container.ts:95:30)
    at ServiceContainer.getInjectorContext (/var/www/deepkit-test/node_modules/@deepkit/app/src/service-container.ts:115:14)
```

In the docs:

```typescript
class UserController {
    constructor(private database: Database) {}
```    

The example app though uses the concrete implementation in construtor

```typescript
@http.controller()
export class MainController {
    constructor(protected logger: LoggerInterface, protected database: SQLiteDatabase) {
    }
```

**Comment by marcj** [comment]
Yes, it probably should inject the sub class of Database. To work around it, you can register your SqliteDatabase as Database via

   providers: [{provive: Database, useClass: SqliteDatabase}]

**Comment by colorcube** [comment]
Indeed that works.
I overlooked that in the docs.
