### ISSUE TITLE
groupBy() with mongo throws error

### ISSUE THREAD

**Issue by colorcube** [deepkit/deepkit-framework#408]
Query example
 
 ```typescript
const res = await db.query(MyModel)
                     .groupBy('a')
                     .withSum('b', 'bSum')
                     .find();
```

throws error

```
    MongoError: Could not deserialize type SpecialisedResponse: ValidationError: Validation error:
    cursor.firstBatch.0._id(type): Cannot convert bson type OBJECT to MongoId. invalid BSON type

      100 |                     }
      101 |
    > 102 |                     this.current.reject(new MongoError(`Could not deserialize type ${stringifyType(this.current.responseType)}: ${error}`));
          |                                         ^
      103 |                     return;
      104 |                 }
      105 |             }

      at AggregateCommand.handleResponse (../../../../deepkit-framework/packages/mongo/src/client/command/command.ts:102:41)
      at MongoConnection.onResponse (../../../../deepkit-framework/packages/mongo/src/client/connection.ts:378:34)
      at ResponseParser.feed (../../../../deepkit-framework/packages/mongo/src/client/connection.ts:535:22)
      at Socket.<anonymous> (../../../../deepkit-framework/packages/mongo/src/client/connection.ts:312:66)
      at async AggregateCommand.execute (../../../../deepkit-framework/packages/mongo/src/client/command/aggregate.ts:88:21)
      at async MongoConnection.execute (../../../../deepkit-framework/packages/mongo/src/client/connection.ts:400:20)
      at async MongoQueryResolver.find (../../../../deepkit-framework/packages/mongo/src/query.resolver.ts:313:31)
      at async MongoDatabaseQuery.find (../../../../deepkit-framework/packages/orm/src/query.ts:699:20)
```

By the way, groupBy('a.aa') is not supported

**Comment by marcj** [comment]
what is MyModel?

**Comment by colorcube** [comment]
Here's the adapted example from the docs

```typescript
@entity.name('file')
class File {
    public _id: MongoId & PrimaryKey = '';
    created: Date = new Date;

    downloads: number = 0;

    category: string = 'none';

    constructor(public path: string & Index) {
    }
}


await db.persist(cast<File>({path: 'file1', category: 'images'}),
                 cast<File>({path: 'file2', category: 'images'}),
                 cast<File>({path: 'file3', category: 'pdfs'}));

await db.query(File).filter({path: 'file1'}).patchOne({$inc: {downloads: 15}});
await db.query(File).filter({path: 'file2'}).patchOne({$inc: {downloads: 5}});

// works
const res = await db.query(File).groupBy('category').find();
console.log(res);

// exception
const res2 = await db.query(File)
                    .groupBy('category')
                    .withSum('downloads', 'downloadsSum')
                    .find();
console.log(res2);
```

**Comment by colorcube** [comment]
In another context I tried to use AggregateCommand with a custom pipeline which results in the same error.

**Comment by colorcube** [comment]
When using `AggregateCommand` and setting `specialisedResponse = undefined;` my custom query works fine

```typescript
        specialisedResponse = undefined;
        const res = await this.sendAndWait<AggregateMessage, Response>(cmd, undefined, specialisedResponse);
```    

When I provide a matching `resultSchema` it works without that hack. I suggest to have the option to have no `resultSchema/specialisedResponse` for custom/raw `AggregateCommand` calls. And I suggest `AggregateCommand` should be exported by deepkit/mongo;

Back to the `groupBy().withSum()`. 
My assumption: `withSum` has to provide a `resultSchema` which matches the result. Otherwise the schema from the model (File) is used which doesn't match the result?!

I don't think I can dig deeper.

**Comment by colorcube** [comment]
Here's an test case where providing a resultSchema throws an error too:

```
» node --max_old_space_size=3048 node_modules/jest/bin/jest.js --forceExit --no-cache packages/mongo/tests/mongo-aggregate.spec.ts                                                                 1 ↵
  console.log
    mongo raw response {
      cursor: {
        firstBatch: [
          {
            _id: { prodId: 'AA' },
            uniqueIds: [ '63e77cacb5f2ec3c71000002', '63e77cabb5f2ec3c71000001' ],
            count: 2
          }
        ],
        id: 0n,
        ns: 'testing.test_aggregate'
      },
      ok: 1
    }

      at AggregateCommand.handleResponse (src/client/command/command.ts:93:29)

 FAIL  packages/mongo/tests/mongo-aggregate.spec.ts (8.778 s)
  ✕ raw AggregateCommand (290 ms)

  ● raw AggregateCommand

    MongoError: Could not deserialize type SpecialisedResponse: ValidationError: Validation error:
    cursor.firstBatch.0.uniqueIds.0(type): Cannot convert bson type OID to string. invalid BSON type
```

Test case:

```typescript
import { expect, test } from '@jest/globals';
import {
    entity,
    MongoId,
    PrimaryKey,
    ReflectionClass,
} from '@deepkit/type';
import { createDatabase } from './utils';
import { AggregateCommand } from '../src/client/command/aggregate';

Error.stackTraceLimit = 100;

@entity.name('Model').collection('test_aggregate')
export class Model {
    _id: MongoId & PrimaryKey = '';

    prodId: string = '';

    constructor(public name: string) {
    }
}


test('raw AggregateCommand', async () => {
    const db = await createDatabase('testing');
    await db.query(Model).deleteMany();

    const item = new Model('foo');
    item.prodId = 'AA';

    const item2 = new Model('foo2');
    item2.prodId = 'AA';

    const item3 = new Model('foo3');
    item3.prodId = 'BB';

    await db.persist(item);
    await db.persist(item2);
    await db.persist(item3);

    /* Expected Query result example
    [
      {
        _id: { prodId: '12345678' },
        uniqueIds: [ '63e69569a82a66fedb000001', '63e69569a82a66fedb000002' ],
        count: 2
      },
      {
        _id: { prodId: '22345678' },
        uniqueIds: [ '63e69569a82a66fedb000003', '63e69569a82a66fedb000004' ],
        count: 2
      }
    ]
     */

    class ResultId {
        prodId!: string;
    }

    class DoubleEntries {
        _id!: ResultId;
        uniqueIds!: string[];
        count!: number;
    }

    // this will find records with the same prodId and list their _id
    const pipeline = [
        {
            $group: {
                _id: {prodId: '$prodId'}, 
                uniqueIds: {$addToSet: '$_id'}, 
                count: {$sum: 1},
            },
        },
        {
            $match: {
                count: {$gte: 2},
            },
        },
    ];

    const resultSchema = ReflectionClass.from(DoubleEntries);
    const schema = ReflectionClass.from(Model);
    const command = new AggregateCommand(schema, pipeline, resultSchema);
    const res = await db.adapter.client.execute(command);

    console.log(res);
});

```

**Comment by marcj** [comment]
`uniqueIds!: string` should be `uniqueIds!: MongoId` as they have binary ObjectIds

**Comment by colorcube** [comment]
indeed

**Comment by marcj** [comment]
Would be awesome if we could infer the return type from the `pipeline` variable automatically. then we could provide a new API for that that doesn't use the rather unhandy `AggregateCommand`

**Comment by marcj** [comment]
The original issue was fixed in https://github.com/deepkit/deepkit-framework/commit/68770a6cd85174bff70574432510138b51e8acc6. Not sure if anything else is open, if so please create a new issue.

**Comment by colorcube** [comment]
I can confirm it's fixed
Thanks
