### ISSUE TITLE
[ORM] mongodb BSONError: No template found for 0 for Array<{...}>

### ISSUE THREAD

**Issue by CristianPi** [deepkit/deepkit-framework#444]
```ts
  references: Array<{
    cls: string,
    id: MongoId
  }> = [];
```

The error is not very clear, but is does not like that **Array** the way i declared it.

```bash
  should create an entity - autocommit disable
/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:724
            throw new model_js_1.BSONError(`No template found for ${member.type.kind}`);
                  ^

BSONError: No template found for 0
    at handleObjectLiteral (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:724:19)
    at sizerObjectLiteral (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:597:5)
    at /home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:1201:96
    at executeTemplates (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/type/dist/cjs/src/serializer.js:651:13)
    at sizerArray (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:1061:43)
    at /home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:1211:96
    at executeTemplates (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/type/dist/cjs/src/serializer.js:651:13)
    at handleObjectLiteral (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:722:54)
    at sizerObjectLiteral (/home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:597:5)
    at /home/cristian/IdeaProjects/base-monorepo-nodejs/node_modules/@deepkit/bson/dist/cjs/src/bson-serializer.js:1202:104

```

It works using an interface/class and using []

```ts
  references: ref[] = [];
```

**Comment by marcj** [comment]
I just added tests to show that this works as intended, see https://github.com/deepkit/deepkit-framework/commit/373a69857410ec5cac376a61bcd63078e5d9596d. We also have templates assigned to kind=0, so I'm not sure where this error is coming from.

So, please post a full reproduction example if you still get this error in the newest version
