### ISSUE TITLE
Undefined dependency "ApplicationServerConfig" of ApplicationServer

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#473]
```
33 |  *
34 |  * @public
35 |  */
36 | export class CustomError extends Error {
37 |     constructor(message = '') {

38 |         super(message);
            ^
DependenciesUnmetError: Undefined dependency "config: UnknownTypeName:() => __\u{3a9}ApplicationServerConfig" of ApplicationServer(✓, ✓, ✓, ✓, ?). Type has no provider in no scope.
      at new CustomError (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/core/dist/esm/src/core.js:38:8)
      at new InjectorError (:1:32)
      at new DependenciesUnmetError (:1:32)
      at createFactoryProperty (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/injector.js:579:18)
      at createFactory (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/injector.js:445:26)
      at buildProvider (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/injector.js:346:22)
      at build (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/injector.js:288:31)
      at new Injector (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/injector.js:191:8)
      at getOrCreateInjector (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/injector/dist/esm/src/module.js:381:24)
      at process (/Users/marcus-sa/Git/marcus-sa/deepkitx/node_modules/@deepkit/app/dist/esm/src/service-container.js:95:8)
```

**Comment by marcus-sa** [comment]
NB: was run using Bun

**Comment by marcus-sa** [comment]
No longer an issue with Bun
