### ISSUE TITLE
Node InferType did not pass test 'isEntityName'

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#509]
The original [issue](https://github.com/deepkit/deepkit-framework/issues/455) was marked as complete even though it wasn't fixed.

#### Reproduction
```ts
function a<T>(t: T): T {
    return b<T>(t);
}

function b<T>(t: T): T {
    return t;
}

a(1);
```

#### Workaround
Disable reflection for the specific scope
```ts
/** @reflection never */
```

**Comment by marcus-sa** [comment]
@marcj my assumption is that it's because of different TypeScript versions. This was tested using 5.2.2

**Comment by marcus-sa** [comment]
I had the same issue when I tried to add Nx to the repository, where I also upgraded TypeScript to 5.2.2

**Comment by marcj** [comment]
I don't know. The old PR and your patch doesn't fix it, it basically disables the whole sextion since found is then always false, iirc. need to look into it closer to figure out a solution

**Comment by marcus-sa** [comment]
@marcj I'm gonna have a look at it

**Comment by marcus-sa** [comment]
@marcj upgrading the TypeScript version to 5.2.2 in this repository fixes it for me
https://github.com/deepkit/deepkit-framework/pull/510
However, now I'm getting an error related to using interfaces as dependencies instead
```
✖  nx run example-cli:build
	file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:628
                   throw new DependenciesUnmetError(`Undefined dependency "${options.name}: ${type}" of ${of}. Type has no provider in ${fromScope ? 'scope ' + fromScope : 'no scope'}.`);
                         ^
       
       DependenciesUnmetError: Undefined dependency "logger: LoggerInterface" of BuildController(?). Type has no provider in scope cli.
           at Injector.createFactoryProperty (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:628:19)
           at Injector.createFactory (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:473:32)
           at Injector.buildProvider (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:373:28)
           at Injector.build (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:315:37)
           at new Injector (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:216:14)
           at RootAppModule.getOrCreateInjector (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/module.js:390:25)
           at InjectorContext.getInjector (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:835:23)
           at InjectorContext.getRootInjector (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/injector/dist/esm/src/injector.js:838:21)
           at ServiceContainer.process (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/app/dist/esm/src/service-container.js:99:30)
           at ServiceContainer.getInjector (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/app/dist/esm/src/service-container.js:157:14)
```

**Comment by marcus-sa** [comment]
@marcj these PRs fixed the issue for me
https://github.com/deepkit/deepkit-framework/pull/510
https://github.com/deepkit/deepkit-framework/pull/511

**Comment by marcus-sa** [comment]
@timvandam did you also have this issue with TypeScript 5.2.2 or was it a different version?

**Comment by timvandam** [comment]
idk I forgot

**Comment by marcj** [comment]
FYI TypeScript 4.9.5 works fine with this code

**Comment by marcus-sa** [comment]
@marcj the following patch to TypeScript fixes the issue for me
```patch
diff --git a/node_modules/typescript/lib/typescript.js b/node_modules/typescript/lib/typescript.js
index 86ab90b..dc72ecb 100644
--- a/node_modules/typescript/lib/typescript.js
+++ b/node_modules/typescript/lib/typescript.js
@@ -87586,7 +87586,7 @@ ${lanes.join("\n")}
         [183 /* TypeReference */]: function visitEachChildOfTypeReferenceNode(node, visitor, context, nodesVisitor, nodeVisitor, _tokenVisitor) {
           return context.factory.updateTypeReferenceNode(
             node,
-            Debug.checkDefined(nodeVisitor(node.typeName, visitor, isEntityName)),
+            Debug.checkDefined(nodeVisitor(node.typeName, visitor, node => isTypeNode(node) || isEntityName(node))),
             nodesVisitor(node.typeArguments, visitor, isTypeNode)
           );
         },
```

**Comment by marcus-sa** [comment]
@marcj the output code does look correct here
Input
```ts
export function createModule<T1 extends CreateModuleDefinition>(
  options: T1,
  name: string = '',
): AppModuleClass<ExtractClassType<T1['config']>> {
  return class AnonAppModule extends AppModule<T1> {
    constructor(config?: PartialDeep<ExtractClassType<T1['config']>>) {
      super(options, name);
      if (config) {
        this.configure(config);
      }
    }
  } as any;
}
```
Output
```js
function createModule(options, name = '') {
    return class AnonAppModule extends AppModule {
        constructor(config) {
            super(options, name);
            if (config) {
                this.configure(config);
            }
        }
        static { this.__type = [() => options, () => AppModule, 'config', 'constructor', () => options, 'AnonAppModule', 'PPdi!h!!qe!!!j7"P"2#8"0$5Pdi%h!!qe!!!j6"w&']; }
    };
}
createModule.__type = ['options', 'name', () => "", () => __ΩAppModuleClass, () => __ΩExtractClassType, "config", 'createModule', 'P"2!&2">#".&fo%"o$"/\''];
```

**Comment by marcus-sa** [comment]
https://github.com/microsoft/TypeScript/issues/56480

**Comment by moui72** [comment]
I discovered that this issue only happens for me if `NODE_ENV=development`

I don't get this error when `NODE_ENV=production`, `NODE_ENV=`, or `NODE_ENV=potato`

**Comment by marcj** [comment]
that's weird

**Comment by moui72** [comment]
I think it's because the error is thrown in `Debug.assertNode` and `Debug.*` is ignored when NODE_ENV is not development?

**Comment by marcus-sa** [comment]
No longer an issue for me with latest TypeScript versions.

**Comment by pcfleischer** [comment]
for me updating typescipt worked... `npm update typescript`, it only updated a single minor revision so it could just be a package.lock.json issue

<img width="696" alt="Image" src="https://github.com/user-attachments/assets/37e943ed-c716-4a96-9080-2c9c28eb67e0" />

**Comment by marcus-sa** [comment]
Still occurs with TypeScript version 5.8.3

**Comment by marcus-sa** [comment]
> I discovered that this issue only happens for me if `NODE_ENV=development`
> 
> I don't get this error when `NODE_ENV=production`, `NODE_ENV=`, or `NODE_ENV=potato`
> 
> ```
> core-api:  NX   Running target build for project core-api and 11 tasks it depends on:
> core-api: > nx run shared-common:build
> core-api: Compiling TypeScript files for project "shared-common"...
> core-api: Done compiling TypeScript files for project "shared-common".
> core-api: > nx run shared-deepkit:build
> core-api: Compiling TypeScript files for project "shared-deepkit"...
> core-api: Done compiling TypeScript files for project "shared-deepkit".
> core-api: > nx run shared-auth:build
> core-api: Compiling TypeScript files for project "shared-auth"...
> core-api: Done compiling TypeScript files for project "shared-auth".
> core-api: > nx run core-condition-parser:build
> core-api: Compiling TypeScript files for project "core-condition-parser"...
> core-api: Done compiling TypeScript files for project "core-condition-parser".
> core-api: > nx run shared-typeorm:build
> core-api: Compiling TypeScript files for project "shared-typeorm"...
> core-api: Done compiling TypeScript files for project "shared-typeorm".
> core-api: > nx run shared-nestjs:build
> core-api: Compiling TypeScript files for project "shared-nestjs"...
> core-api: /Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92389
> core-api:   Debug.assertNode(visitedNode, test);
> core-api:         ^
> core-api: Error: Debug Failure. False expression: Unexpected node.
> core-api: Verbose Debug Information: Node InferType did not pass test 'isEntityName'.
> core-api:     at visitNode (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92389:9)
> core-api:     at visitEachChildOfTypeReferenceNode (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92787:26)
> core-api:     at visitEachChild (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92628:33)
> core-api:     at searchArgument (/Users/tyler.peckenpaugh/pager/titan/node_modules/@deepkit/type-compiler/dist/cjs/src/compiler.js:1967:32)
> core-api:     at visitArrayWorker (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92442:49)
> core-api:     at visitNodes2 (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92413:19)
> core-api:     at visitEachChildOfTypeReferenceNode (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92788:7)
> core-api:     at visitEachChild (/Users/tyler.peckenpaugh/pager/titan/node_modules/typescript/lib/typescript.js:92628:33)
> core-api:     at ReflectionTransformer.resolveTypeParameter (/Users/tyler.peckenpaugh/pager/titan/node_modules/@deepkit/type-compiler/dist/cjs/src/compiler.js:1976:54)
> core-api:     at ReflectionTransformer.extractPackStructOfTypeReference (/Users/tyler.peckenpaugh/pager/titan/node_modules/@deepkit/type-compiler/dist/cjs/src/compiler.js:1851:22)
> ```
> 
> I think it's because the error is thrown in `Debug.assertNode` and `Debug.*` statements are ignored when `NODE_ENV` is not `development`?

This happens to me as well.
