### ISSUE TITLE
Problem with optionally undefined property

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#69]
In this example
```
class TestClass {
  constructor(
    @(f.type(Class1).optional)
    public v1: Class1 | undefined,
    @f.type(Number)
    public v2: number
  ) {}
}
```

I get the following error

```
Error: TestClass::constructor::v1 type mismatch. Given Class1, but declared is Object or undefined. The actual type is an object, but you specified a class in @t.type(T).
Please declare a type or use @t.map(Class1) for 'v1: {[k: string]: Class1}'.
    at /home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/@deepkit-type-virtual-b5255d5543/0/cache/@deepkit-type-npm-1.0.0-alpha.6-405eb5f600-33f9be16af.zip/node_modules/@deepkit/type/src/decorators.ts:2385:19
    at fn (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/@deepkit-type-virtual-b5255d5543/0/cache/@deepkit-type-npm-1.0.0-alpha.6-405eb5f600-33f9be16af.zip/node_modules/@deepkit/type/src/decorators.ts:1876:9)
    at /home/ulf/sana-sierra-mono-1/lerna-project-root/server/validate.ts:12:37
    at DecorateConstructor (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/cache/reflect-metadata-npm-0.1.13-c525998e20-629101e6c8.zip/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/cache/reflect-metadata-npm-0.1.13-c525998e20-629101e6c8.zip/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/home/ulf/sana-sierra-mono-1/lerna-project-root/server/validate.ts:4:92)
    at Object.<anonymous> (/home/ulf/sana-sierra-mono-1/lerna-project-root/server/validate.ts:84:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/ts-node-virtual-460cd590c0/0/cache/ts-node-npm-9.0.0-7f58a021c2-49d2ab087f.zip/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

It would work with deepkit with `public v1?: Class1`, but in this case I'd like to use `Class1 | undefined` since there are more mandatory parameters for this constructors!

Many thanks

**Comment by marcj** [comment]
Thanks, I removed that check entirely as TypeScript's reflection system is too weak and it created more issues than expected. Fixed in alpha7.
