### ISSUE TITLE
[type] identifier 'global' has already been declared

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#89]
Fails to require `@deepkit/type` in a jest test suite, because `global` is a "*reserved*" identifier.

```
/node_modules/@deepkit/type/dist/cjs/src/model.js:23
    const global = {
          ^

    SyntaxError: Identifier 'global' has already been declared

      at Runtime.createScriptFromCode (../../../../../../../../../../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (../../../../../../../../../../node_modules/@deepkit/type/index.ts:12:1)
```

Here's a quick fix for now using [`patch-package`](https://github.com/ds300/patch-package):
```
diff --git a/node_modules/@deepkit/type/dist/cjs/src/model.js b/node_modules/@deepkit/type/dist/cjs/src/model.js
index 5f1fec9..f6cdbce 100644
--- a/node_modules/@deepkit/type/dist/cjs/src/model.js
+++ b/node_modules/@deepkit/type/dist/cjs/src/model.js
@@ -20,11 +20,9 @@ var UnpopulatedCheck;
     UnpopulatedCheck[UnpopulatedCheck["Throw"] = 1] = "Throw";
     UnpopulatedCheck[UnpopulatedCheck["ReturnSymbol"] = 2] = "ReturnSymbol";
 })(UnpopulatedCheck = exports.UnpopulatedCheck || (exports.UnpopulatedCheck = {}));
-const global = {
-    RegisteredEntities: {},
-    unpopulatedCheck: UnpopulatedCheck.Throw,
-    enableForwardRefDetection: true,
-};
+global.RegisteredEntities = {};
+global.unpopulatedCheck = UnpopulatedCheck.Throw;
+global.enableForwardRefDetection = true;
 function getGlobalStore() {
     return global;
 }

```

**Comment by marcj** [comment]
That's weird, because I use Jest as well and never got such an error. Which version do you use?

**Comment by marcj** [comment]
Mh ok, we can easily change that variable, no problemo.

**Comment by marcus-sa** [comment]
Awesome, cheers man!

**Comment by marcj** [comment]
is fixed in master
